name: my_flutter_projecttts

packages:
  - my_flutter_projecttts/features/*
  - my_flutter_projecttts/shared/*
  - my_flutter_projecttts/core
  - my_flutter_projecttts

categories:
  features:
    - my_flutter_projecttts/features/*
  shared:
    - my_flutter_projecttts/shared/*
  core:
    - my_flutter_projecttts/core
  project:
    - my_flutter_projecttts
  # seprated Shared
  components:
    - my_flutter_projecttts/shared/components
  dependency:
    - my_flutter_projecttts/shared/packages
  l10n:
    - my_flutter_projecttts/shared/l10n
  preferences:
    - my_flutter_projecttts/shared/preferences

scripts:
  bootstrap:
    run: melos bootstrap
    description: "Install all dependencies in all packages."

  pub_get:
    run: melos exec -- pub get
    description: "Run 'pub get' in all packages."

  clean:
    run: melos exec -- flutter clean
    description: "Clean all packages."

  test:
    run: melos exec -- flutter test
    description: "Run tests in all packages."

  format:
    run: melos exec -- flutter format .
    description: "Format all packages."

  analyze:
    run: melos exec -- flutter analyze
    description: "Analyze all packages."

  publish_to_none:
    run: dart run scripts/add_publish_to_none.dart
    description: "Add pubspec_overrides.yaml to all packages."

  analyzer_macros:
    run: dart run scripts/add_analyzer_experiment.dart
    description: "Add analyzer macros experimental feature to all packages."

  # dependency_adder:
  #   run: dart run scripts/dependency_adder.dart
  #   description: "Add dependencies and dev_dependencies to all packages."
    
  add_dependencies_to_features:
    run: |
      melos exec --category="features" -- flutter pub add core --path=../../core && melos exec --category="features" -- flutter pub add packages --path=../../packages
    description: "Add dependencies to all packages in the features category."

  add_dev_dependencies_to_features:
    run: |
      melos exec --category="features" -- flutter pub add dev:bloc_test dev:json_serializable dev:freezed dev:build_runner
    description: "Add dev dependencies to all packages in the features category."
  

  add_dependencies_to_core:
    run: |
      melos exec --category="core" -- flutter pub add packages --path=../shared/packages && melos exec --category="core" -- flutter pub add preferences --path=../shared/preferences
    description: "Add dependencies to all packages in the core category."

  # add_dev_dependencies_to_core:
  #   run: |
  #     melos exec --category="core" -- flutter pub add --dev bloc_test json_serializable freezed build_runner
  #   description: "Add dev dependencies to all packages in the core category."

  add_dependencies_to_l10n:
    run: |
      melos exec --category="l10n" -- flutter pub add intl && melos exec --category="l10n" -- flutter pub add flutter_localizations --sdk=flutter && melos exec --category="l10n" -- flutter pub add  packages --path=../packages && melos exec --category="l10n" -- flutter pub add --dev intl_utils 
    description: "Add dependencies to all packages in the core category."
  add_flutter_intl:
    run:  melos exec --category="l10n" -- dart run scripts/add_flutter_intl.dart
    description: "Add tag Flutter Intl"
  generate:l10n:
    run: |
      melos exec --category="l10n" -- dart run scripts/delete_generated_files.dart && melos exec --category="l10n" -- flutter pub get && melos exec --category="l10n" -- flutter pub run intl_utils:generate 
    description: "Clean And Generate Locales"
